# Generated by Django 3.2.6 on 2021-10-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0002_auto_20211018_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('country', 'city')},
        ),
    ]
