# Generated by Django 3.2.6 on 2021-10-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0003_auto_20211018_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='date_apply',
            field=models.DateField(auto_now_add=True),
        ),
    ]
