# Generated by Django 3.2.6 on 2021-10-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0004_alter_apply_date_apply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='this is a subtitle', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='date_apply',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
