# Generated by Django 3.2.6 on 2021-10-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0005_auto_20211019_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Address',
            new_name='address',
        ),
    ]
