# Generated by Django 3.2.6 on 2021-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0006_rename_address_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/uploads/avatar/%Y/%m'),
        ),
    ]
