# Generated by Django 3.2.6 on 2021-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
