# Generated by Django 3.2.6 on 2021-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0008_post_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['is_accepted']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city']},
        ),
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
