# Generated by Django 3.2.6 on 2021-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0010_auto_20211204_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='logo_image',
            field=models.ImageField(default='img', upload_to='static/uploads/images/%Y/%m'),
            preserve_default=False,
        ),
    ]
