# Generated by Django 3.2.6 on 2021-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0011_employer_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
