# Generated by Django 3.2.6 on 2021-12-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0012_apply_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apply',
            options={'ordering': ['date_apply']},
        ),
        migrations.AlterField(
            model_name='apply',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='jobReferralApp.jobapplicant'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accept'), ('R', 'Refuse')], default='P', max_length=1),
        ),
    ]
