# Generated by Django 3.2.6 on 2021-12-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobReferralApp', '0013_auto_20211220_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employer', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='cover_letter',
            field=models.FileField(null=True, upload_to='static/uploads/coverLetter/%Y/%m'),
        ),
    ]
